# Generated by Django 5.0.3 on 2024-04-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
