# Generated by Django 5.0.3 on 2024-04-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
