# Generated by Django 5.0.3 on 2024-04-16 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0007_task_status_alter_project_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 14, 42, 20, 195892)),
        ),
    ]
