# Generated by Django 5.0.3 on 2024-04-28 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0011_task_assigned_to_alter_project_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 22, 21, 55, 90739)),
        ),
    ]
