# Generated by Django 5.0.3 on 2024-05-12 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0012_project_assigned_alter_project_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 11, 0, 46, 490676)),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='todo', max_length=100),
        ),
    ]
