# Generated by Django 5.0.3 on 2024-05-12 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0014_alter_project_start_userstory_task_usid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 11, 20, 21, 175241)),
        ),
    ]
