# Generated by Django 5.0.3 on 2024-05-19 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0016_alter_project_start_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='teams',
            field=models.ManyToManyField(related_name='members', to='dynamo.team'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 14, 23, 5, 562379)),
        ),
    ]
