# Generated by Django 5.0.3 on 2024-05-21 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0017_userrole_teams_alter_project_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 0, 33, 52, 116399)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 0, 33, 52, 116399)),
        ),
    ]
