# Generated by Django 5.0.3 on 2024-05-24 11:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0019_alter_project_deadline_alter_project_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 5, 24, 16, 36, 16, 884351)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 16, 36, 16, 884351)),
        ),
        migrations.CreateModel(
            name='PTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamo.project')),
            ],
        ),
    ]
