# Generated by Django 5.0.3 on 2024-05-24 12:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0020_alter_project_deadline_alter_project_start_pteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 5, 24, 17, 43, 26, 3819)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 17, 43, 26, 3819)),
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='teams',
        ),
        migrations.AddField(
            model_name='userrole',
            name='teams',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dynamo.team'),
        ),
    ]
